# Generated by Django 5.0.9 on 2026-09-15 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_services', models.PositiveIntegerField(default=2)),
                ('filter_replacement', models.BooleanField(default=False)),
                ('emergency_service', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One benefit per line - shown as a bullet list.')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AMC plan',
                'verbose_name_plural': 'AMC plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='bi-tools', max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AMCSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amc_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.amcplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amc_subscriptions', to='products.product')),
            ],
            options={
                'verbose_name': 'AMC subscription',
                'verbose_name_plural': 'AMC subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='technicians/')),
                ('area', models.CharField(blank=True, max_length=140)),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link a login account so the technician can use the dashboard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair / Service'), ('maintenance', 'Maintenance'), ('amc', 'AMC Visit')], default='repair', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('problem_description', models.TextField(blank=True, help_text='Describe the problem or any additional notes.')),
                ('attachment', models.FileField(blank=True, help_text='Optional photo or short video of the issue.', null=True, upload_to='service_requests/')),
                ('preferred_date', models.DateField(default=django.utils.timezone.now)),
                ('preferred_time', models.CharField(blank=True, default='10:00 AM - 1:00 PM', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Technician Assigned'), ('accepted', 'Accepted by Technician'), ('on_the_way', 'On the Way'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='products.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services.service')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='services.technician')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
